/**
 * Banco Galicia - Hackaton 2019
 * Definición de la API para el Hackaton de Banco Galicia
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CustomerData { 
    id?: number;
    firstName?: string;
    lastName?: string;
    docType?: string;
    docNumber?: string;
    birthDate?: string;
    mobilePhoneNumber?: string;
    emailAddress?: string;
    thirdPartyUserId?: string;
    streetName?: string;
    streetNumber?: string;
    city?: string;
    state?: string;
    zip?: string;
    lat?: string;
    lng?: string;
    gender?: string;
}
